package connect.db.green.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GROUP_MEMBER_ENTITY".
*/
public class GroupMemberEntityDao extends AbstractDao<GroupMemberEntity, Long> {

    public static final String TABLENAME = "GROUP_MEMBER_ENTITY";

    /**
     * Properties of entity GroupMemberEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property Identifier = new Property(1, String.class, "identifier", false, "IDENTIFIER");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Avatar = new Property(3, String.class, "avatar", false, "AVATAR");
        public final static Property Address = new Property(4, String.class, "address", false, "ADDRESS");
        public final static Property Role = new Property(5, Integer.class, "role", false, "ROLE");
        public final static Property Nick = new Property(6, String.class, "nick", false, "NICK");
        public final static Property Pub_key = new Property(7, String.class, "pub_key", false, "PUB_KEY");
    }


    public GroupMemberEntityDao(DaoConfig config) {
        super(config);
    }
    
    public GroupMemberEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GROUP_MEMBER_ENTITY\" (" + //
                "\"_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"IDENTIFIER\" TEXT NOT NULL ," + // 1: identifier
                "\"USERNAME\" TEXT NOT NULL ," + // 2: username
                "\"AVATAR\" TEXT NOT NULL ," + // 3: avatar
                "\"ADDRESS\" TEXT NOT NULL ," + // 4: address
                "\"ROLE\" INTEGER," + // 5: role
                "\"NICK\" TEXT," + // 6: nick
                "\"PUB_KEY\" TEXT);"); // 7: pub_key
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GROUP_MEMBER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GroupMemberEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getIdentifier());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getAvatar());
        stmt.bindString(5, entity.getAddress());
 
        Integer role = entity.getRole();
        if (role != null) {
            stmt.bindLong(6, role);
        }
 
        String nick = entity.getNick();
        if (nick != null) {
            stmt.bindString(7, nick);
        }
 
        String pub_key = entity.getPub_key();
        if (pub_key != null) {
            stmt.bindString(8, pub_key);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GroupMemberEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getIdentifier());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getAvatar());
        stmt.bindString(5, entity.getAddress());
 
        Integer role = entity.getRole();
        if (role != null) {
            stmt.bindLong(6, role);
        }
 
        String nick = entity.getNick();
        if (nick != null) {
            stmt.bindString(7, nick);
        }
 
        String pub_key = entity.getPub_key();
        if (pub_key != null) {
            stmt.bindString(8, pub_key);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GroupMemberEntity readEntity(Cursor cursor, int offset) {
        GroupMemberEntity entity = new GroupMemberEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // identifier
            cursor.getString(offset + 2), // username
            cursor.getString(offset + 3), // avatar
            cursor.getString(offset + 4), // address
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // role
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // nick
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // pub_key
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GroupMemberEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdentifier(cursor.getString(offset + 1));
        entity.setUsername(cursor.getString(offset + 2));
        entity.setAvatar(cursor.getString(offset + 3));
        entity.setAddress(cursor.getString(offset + 4));
        entity.setRole(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setNick(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setPub_key(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GroupMemberEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GroupMemberEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GroupMemberEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
