package connect.database.green.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig paramEntityDaoConfig;
    private final DaoConfig contactEntityDaoConfig;
    private final DaoConfig groupEntityDaoConfig;
    private final DaoConfig groupMemberEntityDaoConfig;
    private final DaoConfig recommandFriendEntityDaoConfig;
    private final DaoConfig friendRequestEntityDaoConfig;
    private final DaoConfig conversionEntityDaoConfig;
    private final DaoConfig conversionSettingEntityDaoConfig;
    private final DaoConfig messageEntityDaoConfig;
    private final DaoConfig transactionEntityDaoConfig;

    private final ParamEntityDao paramEntityDao;
    private final ContactEntityDao contactEntityDao;
    private final GroupEntityDao groupEntityDao;
    private final GroupMemberEntityDao groupMemberEntityDao;
    private final RecommandFriendEntityDao recommandFriendEntityDao;
    private final FriendRequestEntityDao friendRequestEntityDao;
    private final ConversionEntityDao conversionEntityDao;
    private final ConversionSettingEntityDao conversionSettingEntityDao;
    private final MessageEntityDao messageEntityDao;
    private final TransactionEntityDao transactionEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        paramEntityDaoConfig = daoConfigMap.get(ParamEntityDao.class).clone();
        paramEntityDaoConfig.initIdentityScope(type);

        contactEntityDaoConfig = daoConfigMap.get(ContactEntityDao.class).clone();
        contactEntityDaoConfig.initIdentityScope(type);

        groupEntityDaoConfig = daoConfigMap.get(GroupEntityDao.class).clone();
        groupEntityDaoConfig.initIdentityScope(type);

        groupMemberEntityDaoConfig = daoConfigMap.get(GroupMemberEntityDao.class).clone();
        groupMemberEntityDaoConfig.initIdentityScope(type);

        recommandFriendEntityDaoConfig = daoConfigMap.get(RecommandFriendEntityDao.class).clone();
        recommandFriendEntityDaoConfig.initIdentityScope(type);

        friendRequestEntityDaoConfig = daoConfigMap.get(FriendRequestEntityDao.class).clone();
        friendRequestEntityDaoConfig.initIdentityScope(type);

        conversionEntityDaoConfig = daoConfigMap.get(ConversionEntityDao.class).clone();
        conversionEntityDaoConfig.initIdentityScope(type);

        conversionSettingEntityDaoConfig = daoConfigMap.get(ConversionSettingEntityDao.class).clone();
        conversionSettingEntityDaoConfig.initIdentityScope(type);

        messageEntityDaoConfig = daoConfigMap.get(MessageEntityDao.class).clone();
        messageEntityDaoConfig.initIdentityScope(type);

        transactionEntityDaoConfig = daoConfigMap.get(TransactionEntityDao.class).clone();
        transactionEntityDaoConfig.initIdentityScope(type);

        paramEntityDao = new ParamEntityDao(paramEntityDaoConfig, this);
        contactEntityDao = new ContactEntityDao(contactEntityDaoConfig, this);
        groupEntityDao = new GroupEntityDao(groupEntityDaoConfig, this);
        groupMemberEntityDao = new GroupMemberEntityDao(groupMemberEntityDaoConfig, this);
        recommandFriendEntityDao = new RecommandFriendEntityDao(recommandFriendEntityDaoConfig, this);
        friendRequestEntityDao = new FriendRequestEntityDao(friendRequestEntityDaoConfig, this);
        conversionEntityDao = new ConversionEntityDao(conversionEntityDaoConfig, this);
        conversionSettingEntityDao = new ConversionSettingEntityDao(conversionSettingEntityDaoConfig, this);
        messageEntityDao = new MessageEntityDao(messageEntityDaoConfig, this);
        transactionEntityDao = new TransactionEntityDao(transactionEntityDaoConfig, this);

        registerDao(ParamEntity.class, paramEntityDao);
        registerDao(ContactEntity.class, contactEntityDao);
        registerDao(GroupEntity.class, groupEntityDao);
        registerDao(GroupMemberEntity.class, groupMemberEntityDao);
        registerDao(RecommandFriendEntity.class, recommandFriendEntityDao);
        registerDao(FriendRequestEntity.class, friendRequestEntityDao);
        registerDao(ConversionEntity.class, conversionEntityDao);
        registerDao(ConversionSettingEntity.class, conversionSettingEntityDao);
        registerDao(MessageEntity.class, messageEntityDao);
        registerDao(TransactionEntity.class, transactionEntityDao);
    }
    
    public void clear() {
        paramEntityDaoConfig.clearIdentityScope();
        contactEntityDaoConfig.clearIdentityScope();
        groupEntityDaoConfig.clearIdentityScope();
        groupMemberEntityDaoConfig.clearIdentityScope();
        recommandFriendEntityDaoConfig.clearIdentityScope();
        friendRequestEntityDaoConfig.clearIdentityScope();
        conversionEntityDaoConfig.clearIdentityScope();
        conversionSettingEntityDaoConfig.clearIdentityScope();
        messageEntityDaoConfig.clearIdentityScope();
        transactionEntityDaoConfig.clearIdentityScope();
    }

    public ParamEntityDao getParamEntityDao() {
        return paramEntityDao;
    }

    public ContactEntityDao getContactEntityDao() {
        return contactEntityDao;
    }

    public GroupEntityDao getGroupEntityDao() {
        return groupEntityDao;
    }

    public GroupMemberEntityDao getGroupMemberEntityDao() {
        return groupMemberEntityDao;
    }

    public RecommandFriendEntityDao getRecommandFriendEntityDao() {
        return recommandFriendEntityDao;
    }

    public FriendRequestEntityDao getFriendRequestEntityDao() {
        return friendRequestEntityDao;
    }

    public ConversionEntityDao getConversionEntityDao() {
        return conversionEntityDao;
    }

    public ConversionSettingEntityDao getConversionSettingEntityDao() {
        return conversionSettingEntityDao;
    }

    public MessageEntityDao getMessageEntityDao() {
        return messageEntityDao;
    }

    public TransactionEntityDao getTransactionEntityDao() {
        return transactionEntityDao;
    }

}
