package connect.database.green.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "FRIEND_REQUEST_ENTITY".
 */
@Entity
public class FriendRequestEntity implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long _id;

    @NotNull
    private String pub_key;

    @NotNull
    private String address;
    private String avatar;
    private String username;
    private String tips;
    private Integer source;
    private Integer status;
    private Integer read;

    @Generated
    public FriendRequestEntity() {
    }

    public FriendRequestEntity(Long _id) {
        this._id = _id;
    }

    @Generated
    public FriendRequestEntity(Long _id, String pub_key, String address, String avatar, String username, String tips, Integer source, Integer status, Integer read) {
        this._id = _id;
        this.pub_key = pub_key;
        this.address = address;
        this.avatar = avatar;
        this.username = username;
        this.tips = tips;
        this.source = source;
        this.status = status;
        this.read = read;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    @NotNull
    public String getPub_key() {
        return pub_key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPub_key(@NotNull String pub_key) {
        this.pub_key = pub_key;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTips() {
        return tips;
    }

    public void setTips(String tips) {
        this.tips = tips;
    }

    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getRead() {
        return read;
    }

    public void setRead(Integer read) {
        this.read = read;
    }

}
