package connect.database.green.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import connect.database.green.bean.ContactEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTACT_ENTITY".
*/
public class ContactEntityDao extends AbstractDao<ContactEntity, Long> {

    public static final String TABLENAME = "CONTACT_ENTITY";

    /**
     * Properties of entity ContactEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Uid = new Property(1, String.class, "uid", false, "UID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Avatar = new Property(3, String.class, "avatar", false, "AVATAR");
        public final static Property Ou = new Property(4, String.class, "ou", false, "OU");
        public final static Property PublicKey = new Property(5, String.class, "publicKey", false, "PUBLIC_KEY");
        public final static Property EmpNo = new Property(6, String.class, "empNo", false, "EMP_NO");
        public final static Property Mobile = new Property(7, String.class, "mobile", false, "MOBILE");
        public final static Property Gender = new Property(8, Integer.class, "gender", false, "GENDER");
        public final static Property Tips = new Property(9, String.class, "tips", false, "TIPS");
        public final static Property Registed = new Property(10, Boolean.class, "registed", false, "REGISTED");
    }


    public ContactEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ContactEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTACT_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"UID\" TEXT NOT NULL UNIQUE ," + // 1: uid
                "\"NAME\" TEXT," + // 2: name
                "\"AVATAR\" TEXT," + // 3: avatar
                "\"OU\" TEXT," + // 4: ou
                "\"PUBLIC_KEY\" TEXT," + // 5: publicKey
                "\"EMP_NO\" TEXT," + // 6: empNo
                "\"MOBILE\" TEXT," + // 7: mobile
                "\"GENDER\" INTEGER," + // 8: gender
                "\"TIPS\" TEXT," + // 9: tips
                "\"REGISTED\" INTEGER);"); // 10: registed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTACT_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContactEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getUid());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String ou = entity.getOu();
        if (ou != null) {
            stmt.bindString(5, ou);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(6, publicKey);
        }
 
        String empNo = entity.getEmpNo();
        if (empNo != null) {
            stmt.bindString(7, empNo);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(8, mobile);
        }
 
        Integer gender = entity.getGender();
        if (gender != null) {
            stmt.bindLong(9, gender);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(10, tips);
        }
 
        Boolean registed = entity.getRegisted();
        if (registed != null) {
            stmt.bindLong(11, registed ? 1L: 0L);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContactEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getUid());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String ou = entity.getOu();
        if (ou != null) {
            stmt.bindString(5, ou);
        }
 
        String publicKey = entity.getPublicKey();
        if (publicKey != null) {
            stmt.bindString(6, publicKey);
        }
 
        String empNo = entity.getEmpNo();
        if (empNo != null) {
            stmt.bindString(7, empNo);
        }
 
        String mobile = entity.getMobile();
        if (mobile != null) {
            stmt.bindString(8, mobile);
        }
 
        Integer gender = entity.getGender();
        if (gender != null) {
            stmt.bindLong(9, gender);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(10, tips);
        }
 
        Boolean registed = entity.getRegisted();
        if (registed != null) {
            stmt.bindLong(11, registed ? 1L: 0L);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContactEntity readEntity(Cursor cursor, int offset) {
        ContactEntity entity = new ContactEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // avatar
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ou
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // publicKey
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // empNo
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // mobile
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // gender
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // tips
            cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0 // registed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContactEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAvatar(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setOu(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPublicKey(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmpNo(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setMobile(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setGender(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setTips(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setRegisted(cursor.isNull(offset + 10) ? null : cursor.getShort(offset + 10) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContactEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContactEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ContactEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
