package connect.database.green.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import connect.database.green.bean.CurrencyAddressEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CURRENCY_ADDRESS_ENTITY".
*/
public class CurrencyAddressEntityDao extends AbstractDao<CurrencyAddressEntity, Long> {

    public static final String TABLENAME = "CURRENCY_ADDRESS_ENTITY";

    /**
     * Properties of entity CurrencyAddressEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Currency = new Property(1, String.class, "currency", false, "CURRENCY");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property Index = new Property(3, Integer.class, "index", false, "INDEX");
        public final static Property Balance = new Property(4, Long.class, "balance", false, "BALANCE");
        public final static Property Status = new Property(5, Integer.class, "status", false, "STATUS");
        public final static Property Label = new Property(6, String.class, "label", false, "LABEL");
    }


    public CurrencyAddressEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CurrencyAddressEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CURRENCY_ADDRESS_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"CURRENCY\" TEXT NOT NULL ," + // 1: currency
                "\"ADDRESS\" TEXT NOT NULL UNIQUE ," + // 2: address
                "\"INDEX\" INTEGER," + // 3: index
                "\"BALANCE\" INTEGER," + // 4: balance
                "\"STATUS\" INTEGER," + // 5: status
                "\"LABEL\" TEXT);"); // 6: label
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CURRENCY_ADDRESS_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CurrencyAddressEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getCurrency());
        stmt.bindString(3, entity.getAddress());
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(4, index);
        }
 
        Long balance = entity.getBalance();
        if (balance != null) {
            stmt.bindLong(5, balance);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(6, status);
        }
 
        String label = entity.getLabel();
        if (label != null) {
            stmt.bindString(7, label);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CurrencyAddressEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getCurrency());
        stmt.bindString(3, entity.getAddress());
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(4, index);
        }
 
        Long balance = entity.getBalance();
        if (balance != null) {
            stmt.bindLong(5, balance);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(6, status);
        }
 
        String label = entity.getLabel();
        if (label != null) {
            stmt.bindString(7, label);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CurrencyAddressEntity readEntity(Cursor cursor, int offset) {
        CurrencyAddressEntity entity = new CurrencyAddressEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // currency
            cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // index
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // balance
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // status
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // label
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CurrencyAddressEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurrency(cursor.getString(offset + 1));
        entity.setAddress(cursor.getString(offset + 2));
        entity.setIndex(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setBalance(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setLabel(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CurrencyAddressEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CurrencyAddressEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CurrencyAddressEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
