package connect.database.green.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import connect.database.green.bean.RecommandFriendEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECOMMAND_FRIEND_ENTITY".
*/
public class RecommandFriendEntityDao extends AbstractDao<RecommandFriendEntity, Long> {

    public static final String TABLENAME = "RECOMMAND_FRIEND_ENTITY";

    /**
     * Properties of entity RecommandFriendEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Pub_key = new Property(1, String.class, "pub_key", false, "PUB_KEY");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Address = new Property(3, String.class, "address", false, "ADDRESS");
        public final static Property Avatar = new Property(4, String.class, "avatar", false, "AVATAR");
        public final static Property Status = new Property(5, Integer.class, "status", false, "STATUS");
    }


    public RecommandFriendEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RecommandFriendEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECOMMAND_FRIEND_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PUB_KEY\" TEXT NOT NULL UNIQUE ," + // 1: pub_key
                "\"USERNAME\" TEXT NOT NULL ," + // 2: username
                "\"ADDRESS\" TEXT NOT NULL UNIQUE ," + // 3: address
                "\"AVATAR\" TEXT NOT NULL ," + // 4: avatar
                "\"STATUS\" INTEGER);"); // 5: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECOMMAND_FRIEND_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecommandFriendEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getPub_key());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getAddress());
        stmt.bindString(5, entity.getAvatar());
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(6, status);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecommandFriendEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getPub_key());
        stmt.bindString(3, entity.getUsername());
        stmt.bindString(4, entity.getAddress());
        stmt.bindString(5, entity.getAvatar());
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(6, status);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RecommandFriendEntity readEntity(Cursor cursor, int offset) {
        RecommandFriendEntity entity = new RecommandFriendEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // pub_key
            cursor.getString(offset + 2), // username
            cursor.getString(offset + 3), // address
            cursor.getString(offset + 4), // avatar
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecommandFriendEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPub_key(cursor.getString(offset + 1));
        entity.setUsername(cursor.getString(offset + 2));
        entity.setAddress(cursor.getString(offset + 3));
        entity.setAvatar(cursor.getString(offset + 4));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecommandFriendEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecommandFriendEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecommandFriendEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
