package connect.db.green.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONVERSION_ENTITY".
 */
@Entity
public class ConversionEntity implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long _id;

    @Unique
    private String identifier;
    private Integer type;
    private String name;
    private String avatar;
    private String draft;
    private String content;
    private Integer unread_count;
    private Integer top;
    private Integer notice;
    private Integer stranger;
    private Long last_time;

    @Generated
    public ConversionEntity() {
    }

    public ConversionEntity(Long _id) {
        this._id = _id;
    }

    @Generated
    public ConversionEntity(Long _id, String identifier, Integer type, String name, String avatar, String draft, String content, Integer unread_count, Integer top, Integer notice, Integer stranger, Long last_time) {
        this._id = _id;
        this.identifier = identifier;
        this.type = type;
        this.name = name;
        this.avatar = avatar;
        this.draft = draft;
        this.content = content;
        this.unread_count = unread_count;
        this.top = top;
        this.notice = notice;
        this.stranger = stranger;
        this.last_time = last_time;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getDraft() {
        return draft;
    }

    public void setDraft(String draft) {
        this.draft = draft;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getUnread_count() {
        return unread_count;
    }

    public void setUnread_count(Integer unread_count) {
        this.unread_count = unread_count;
    }

    public Integer getTop() {
        return top;
    }

    public void setTop(Integer top) {
        this.top = top;
    }

    public Integer getNotice() {
        return notice;
    }

    public void setNotice(Integer notice) {
        this.notice = notice;
    }

    public Integer getStranger() {
        return stranger;
    }

    public void setStranger(Integer stranger) {
        this.stranger = stranger;
    }

    public Long getLast_time() {
        return last_time;
    }

    public void setLast_time(Long last_time) {
        this.last_time = last_time;
    }

}
