package connect.db.green.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FRIEND_REQUEST_ENTITY".
*/
public class FriendRequestEntityDao extends AbstractDao<FriendRequestEntity, Long> {

    public static final String TABLENAME = "FRIEND_REQUEST_ENTITY";

    /**
     * Properties of entity FriendRequestEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_ID");
        public final static Property Pub_key = new Property(1, String.class, "pub_key", false, "PUB_KEY");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property Avatar = new Property(3, String.class, "avatar", false, "AVATAR");
        public final static Property Username = new Property(4, String.class, "username", false, "USERNAME");
        public final static Property Tips = new Property(5, String.class, "tips", false, "TIPS");
        public final static Property Source = new Property(6, Integer.class, "source", false, "SOURCE");
        public final static Property Status = new Property(7, Integer.class, "status", false, "STATUS");
        public final static Property Read = new Property(8, Integer.class, "read", false, "READ");
    }


    public FriendRequestEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FriendRequestEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FRIEND_REQUEST_ENTITY\" (" + //
                "\"_ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"PUB_KEY\" TEXT NOT NULL ," + // 1: pub_key
                "\"ADDRESS\" TEXT NOT NULL ," + // 2: address
                "\"AVATAR\" TEXT," + // 3: avatar
                "\"USERNAME\" TEXT," + // 4: username
                "\"TIPS\" TEXT," + // 5: tips
                "\"SOURCE\" INTEGER," + // 6: source
                "\"STATUS\" INTEGER," + // 7: status
                "\"READ\" INTEGER);"); // 8: read
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FRIEND_REQUEST_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FriendRequestEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getPub_key());
        stmt.bindString(3, entity.getAddress());
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(5, username);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(6, tips);
        }
 
        Integer source = entity.getSource();
        if (source != null) {
            stmt.bindLong(7, source);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(8, status);
        }
 
        Integer read = entity.getRead();
        if (read != null) {
            stmt.bindLong(9, read);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FriendRequestEntity entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
        stmt.bindString(2, entity.getPub_key());
        stmt.bindString(3, entity.getAddress());
 
        String avatar = entity.getAvatar();
        if (avatar != null) {
            stmt.bindString(4, avatar);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(5, username);
        }
 
        String tips = entity.getTips();
        if (tips != null) {
            stmt.bindString(6, tips);
        }
 
        Integer source = entity.getSource();
        if (source != null) {
            stmt.bindLong(7, source);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(8, status);
        }
 
        Integer read = entity.getRead();
        if (read != null) {
            stmt.bindLong(9, read);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FriendRequestEntity readEntity(Cursor cursor, int offset) {
        FriendRequestEntity entity = new FriendRequestEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.getString(offset + 1), // pub_key
            cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // avatar
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // username
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // tips
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // source
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // status
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8) // read
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FriendRequestEntity entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPub_key(cursor.getString(offset + 1));
        entity.setAddress(cursor.getString(offset + 2));
        entity.setAvatar(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUsername(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTips(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSource(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setStatus(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setRead(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FriendRequestEntity entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FriendRequestEntity entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FriendRequestEntity entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
