package connect.db.green.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GROUP_MEMBER_ENTITY".
 */
@Entity
public class GroupMemberEntity implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long _id;

    @NotNull
    private String identifier;

    @NotNull
    private String username;

    @NotNull
    private String avatar;

    @NotNull
    private String address;
    private Integer role;
    private String nick;
    private String pub_key;

    @Generated
    public GroupMemberEntity() {
    }

    public GroupMemberEntity(Long _id) {
        this._id = _id;
    }

    @Generated
    public GroupMemberEntity(Long _id, String identifier, String username, String avatar, String address, Integer role, String nick, String pub_key) {
        this._id = _id;
        this.identifier = identifier;
        this.username = username;
        this.avatar = avatar;
        this.address = address;
        this.role = role;
        this.nick = nick;
        this.pub_key = pub_key;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    @NotNull
    public String getIdentifier() {
        return identifier;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdentifier(@NotNull String identifier) {
        this.identifier = identifier;
    }

    @NotNull
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(@NotNull String username) {
        this.username = username;
    }

    @NotNull
    public String getAvatar() {
        return avatar;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatar(@NotNull String avatar) {
        this.avatar = avatar;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

    public Integer getRole() {
        return role;
    }

    public void setRole(Integer role) {
        this.role = role;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getPub_key() {
        return pub_key;
    }

    public void setPub_key(String pub_key) {
        this.pub_key = pub_key;
    }

}
