package connect.db.green.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "GROUP_ENTITY".
 */
@Entity
public class GroupEntity implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long _id;

    @NotNull
    @Unique
    private String identifier;
    private String name;
    private String ecdh_key;
    private Integer common;
    private Integer verify;
    private Integer pub;
    private String avatar;
    private String summary;

    @Generated
    public GroupEntity() {
    }

    public GroupEntity(Long _id) {
        this._id = _id;
    }

    @Generated
    public GroupEntity(Long _id, String identifier, String name, String ecdh_key, Integer common, Integer verify, Integer pub, String avatar, String summary) {
        this._id = _id;
        this.identifier = identifier;
        this.name = name;
        this.ecdh_key = ecdh_key;
        this.common = common;
        this.verify = verify;
        this.pub = pub;
        this.avatar = avatar;
        this.summary = summary;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    @NotNull
    public String getIdentifier() {
        return identifier;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIdentifier(@NotNull String identifier) {
        this.identifier = identifier;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEcdh_key() {
        return ecdh_key;
    }

    public void setEcdh_key(String ecdh_key) {
        this.ecdh_key = ecdh_key;
    }

    public Integer getCommon() {
        return common;
    }

    public void setCommon(Integer common) {
        this.common = common;
    }

    public Integer getVerify() {
        return verify;
    }

    public void setVerify(Integer verify) {
        this.verify = verify;
    }

    public Integer getPub() {
        return pub;
    }

    public void setPub(Integer pub) {
        this.pub = pub;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

}
